Add `StepProgress` component
cennznet/app-gov pull request #20
Opened 2022-07-07 01:03 UTC by aidan-starke

## Summary

 - Closes #13 

## Preview

https://user-images.githubusercontent.com/52016903/177667548-1ceb4cab-67d2-4b79-93f0-987083c023be.mov

2022-07-07 22:23 UTC, ken-centrality requested changes
Couple of styling things

 - [x] Instead of grey, use a lighter colour of the purple
 - [ ] Use a solid checkbox, might look better

And one issue that I found

![Screen Shot 2022-07-08 at 10 20 16](https://user-images.githubusercontent.com/97480229/177881365-5acad5a0-9088-4eb6-a949-10550b60e9bb.png)

2022-07-07 22:23 UTC, ken-futureverse commented on apps/gov-website/pages/identity/connect.tsx
> +					<p className="prose mb-8 text-lg">
nice `prose` class!

2022-07-08 01:40 UTC, aidan-starke commented on apps/gov-website/pages/identity/connect.tsx
> +					<p className="prose mb-8 text-lg">
:sunglasses:

2022-07-10 05:30 UTC, ken-centrality requested changes
Looks good, the dialog needs to tweaks to address couple issues, filed them in #31 and #32 

One thing that needs to fix in this PR is the warning here, not sure what causes it

![Screen Shot 2022-07-10 at 17 30 35](https://user-images.githubusercontent.com/97480229/178132623-f92207b8-9d4f-4954-9401-8a7ea04e9b20.png)

2022-07-10 22:32 UTC, ken-centrality submitted a review, later dismissed

2022-07-10 22:32 UTC, ken-futureverse commented on libs/web/hooks/src/useIdentityConnectForm.ts
> +	step: "Await" | "Submit" | "Process" | "Idle";
```suggestion
	step: "Idle" | "Await" | "Submit" | "Process";
```

2022-07-10 22:37 UTC, ken-centrality approved these changes

2022-07-10 22:41 UTC, merged